import Header from '@/components/Header';
import './globals.css';
import Providers from './Providers';
import { ReactNode } from 'react';
import Navbar from '@/components/Navbar';
export const metadata = {
  title: 'IMDB-clone',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps): JSX.Element => {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
//         <Providers>
//           <Header />
//           {children}
//         </Providers>
//       </body>
//     </html>
//   );
// }
